export type Locale = "es" | "en";

export const content = {
  es: {
    meta: {
      title: "D2LE2 Law — Marketplace legal bilingüe",
      description:
        "Ayuda migratoria y leads calificados en un solo lugar. Clientes gratis. Abogados pagan solo al desbloquear. Marketplace tecnológico — no somos un bufete.",
      ogTitle: "D2LE2 Law — Marketplace legal bilingüe",
      ogDescription:
        "Elige tu camino: inicia tu caso o recibe clientes en tiempo real como abogado.",
    },
    header: {
      ticker: [
        "24/7 Disponible",
        "Cliente gratis",
        "Contacto reservado hasta el desbloqueo",
        "Pay-per-lead para abogados",
        "Hold exclusivo 72 horas",
      ],
      speakLang: "Hablamos español",
      nav: [
        { label: "Inicio", href: "#inicio" },
        { label: "Cómo funciona", href: "#como-funciona" },
        { label: "Verificación", href: "#verificacion" },
        { label: "Áreas", href: "#areas" },
        { label: "Abogados", href: "#abogados" },
        { label: "Conexión", href: "#casos" },
        { label: "Beneficios", href: "#beneficios", children: true },
        { label: "Precios", href: "#precios" },
        { label: "Recursos", href: "#recursos" },
        { label: "Registro", href: "/registro" },
        { label: "Contacto", href: "#contacto" },
      ],
      benefitLinks: [
        { label: "Clientes reales", href: "#beneficios" },
        { label: "Panel en tiempo real", href: "#panel" },
        { label: "Soporte bilingüe", href: "#soporte" },
      ],
      phoneSub: "Disponible 24/7",
      ctaClient: "Soy cliente",
      ctaLawyer: "Soy abogado",
      dockChat: "Chat",
      dockCall: "Llamar",
      menuOpen: "Abrir menú",
      langEs: "ES",
      langEn: "EN",
    },
    hero: {
      label: "Gratis para usted · Abogados verificados",
      title: "Ayuda migratoria para su familia,",
      titleAccent: "en un solo lugar.",
      subtitle:
        "Cuente su situación en minutos. Usted no paga. D2LE2 Law no es un bufete ni presta asesoría legal.",
      clientCta: "Soy cliente — iniciar caso",
      lawyerCta: "Soy abogado — registro gratis",
      callCta: "Llamar ahora 24/7",
      zipLabel: "Código postal",
      zipPlaceholder: "Código postal",
      zipSearch: "Buscar",
      zipHint: "Gratis. Abogados verificados cerca de usted.",
      zipError: "Ingrese un ZIP de 5 dígitos.",
      needPrompt: "¿En qué necesita ayuda?",
      needs: [
        { need: "asilo", label: "Asilo" },
        { need: "residencia", label: "Residencia" },
        { need: "familia", label: "Familia" },
        { need: "penal", label: "Corte" },
        { need: "laboral", label: "Trabajo" },
        { need: "otro", label: "Otra situación" },
      ],
      onlineClients: "clientes en línea",
      onlinePros: "profesionales en línea",
      ratingLabel: "Trustpilot",
      ratingScore: "4.9",
      ratingCount: "| 2,500+ Reseñas",
      stats: [
        { value: 15000, prefix: "+", suffix: "", label: "Clientes conectados", labelShort: "Clientes\nconectados" },
        { value: 2500, prefix: "+", suffix: "", label: "Abogados activos", labelShort: "Abogados\nactivos" },
        { value: 98, prefix: "", suffix: "%", label: "Satisfacción", labelShort: "Tasa de\nsatisfacción" },
        { value: 20, prefix: "", suffix: "+", label: "Áreas de práctica", labelShort: "Áreas de\npráctica" },
      ],
      imageAlt: "Interior de un tribunal vacío, sin personas",
    },
    trust: {
      tagline: "Usted cuenta su caso. Nosotros lo conectamos.",
      items: [
        { lines: ["100% gratis", "para usted"] },
        { lines: ["Sus datos", "quedan reservados"] },
        { lines: ["Abogados", "verificados"] },
        { lines: ["Lo atendemos", "en español"] },
        { lines: ["Sin compromiso", "ni presión"] },
      ],
    },
    need: {
      id: "su-caso",
      label: "Su caso",
      title: "¿Se reconoce en alguna de estas situaciones?",
      text: "Toque la que más se parece a la suya. Es gratis y su teléfono no se muestra todavía.",
      cta: "Esta es mi situación",
      items: [
        {
          need: "asilo",
          title: "Tengo una audiencia de asilo",
          text: "No sé qué documentos llevar ni a quién preguntar.",
        },
        {
          need: "residencia",
          title: "Quiero residencia para mi familia",
          text: "Cónyuge, hijos o padres. Necesito empezar bien.",
        },
        {
          need: "penal",
          title: "Tengo una cita en corte",
          text: "Me detuvieron o me citaron. Necesito hablar con un abogado.",
        },
        {
          need: "apelacion",
          title: "Me negaron un trámite",
          text: "Quiero entender opciones con alguien verificado.",
        },
      ],
    },
    audience: {
      id: "caminos",
      clientLabel: "Para clientes",
      clientTitle: "Usted no paga. Ellos se acercan.",
      clientSub:
        "Inmigración y más áreas legales en EE.UU. Cuente el caso. Abogados verificados lo ven sin su nombre. Sin costo para usted.",
      clientCta: "Iniciar mi caso",
      clientCards: [
        { title: "Describe tu caso", text: "Cuéntanos qué necesitas en minutos." },
        { title: "Matching rápido", text: "Abogados verificados ven el asunto sin su nombre ni teléfono." },
        { title: "100% gratis", text: "El cliente nunca paga por usar la plataforma." },
        { title: "Seguro y privado", text: "Publicar no crea relación abogado-cliente." },
      ],
      lawyerLabel: "Para abogados",
      lawyerTitle: "Más clientes. Más control.",
      lawyerSub:
        "Recibe leads calificados, revisa el caso anonimizado y desbloquea solo los que quieres.",
      lawyerCta: "Crear cuenta profesional",
      lawyerCards: [
        { title: "Leads en vivo", text: "Clientes migratorios y legales en tiempo real." },
        { title: "Tú decides", text: "Hold exclusivo 72 horas. Máximo tres asuntos a la vez." },
        { title: "Pay-per-lead", text: "Paga solo al desbloquear. Sin reembolso si rechaza o vence." },
        { title: "Panel pro", text: "Feed, billetera y soporte dedicado." },
      ],
    },
    how: {
      label: "Cómo funciona",
      title: "Tres pasos. Usted no paga.",
      tabClient: "Cliente",
      tabLawyer: "Abogado",
      clientSteps: [
        {
          n: "01",
          title: "Describe tu caso",
          text: "Cuéntanos tu situación migratoria o legal en lenguaje sencillo.",
        },
        {
          n: "02",
          title: "Lo ven sin tus datos",
          text: "El listado muestra el asunto y la jurisdicción. Nombre y teléfono quedan reservados.",
        },
        {
          n: "03",
          title: "Usted elige",
          text: "Converse y decida con quién seguir. El contacto se revela si un abogado asume el caso.",
        },
      ],
      lawyerSteps: [
        {
          n: "01",
          title: "Verifícate",
          text: "Licencia de barra e identidad. Sin eso no hay acceso al contacto.",
        },
        {
          n: "02",
          title: "Revisa leads en vivo",
          text: "Filtra por estado y área. El cliente sigue anónimo hasta el desbloqueo.",
        },
        {
          n: "03",
          title: "Desbloquea 72 horas",
          text: "El cargo no se reembolsa. Si acepta, conversan con datos completos.",
        },
      ],
      panels: [
        {
          t: "Usted publica",
          d: "Cuente el asunto en minutos. Sigue siendo gratis.",
        },
        {
          t: "Sin su nombre",
          d: "El listado muestra el caso, no su teléfono.",
        },
        {
          t: "Usted decide",
          d: "Converse cuando un abogado verificado asuma el contacto.",
        },
      ],
    },
    pulse: {
      id: "en-vivo",
      label: "En vivo",
      title: "Clientes entran. El panel se enciende.",
      text: "Cada caso llega anonimizado al escritorio del abogado correcto. Nombre y teléfono se reservan hasta el desbloqueo.",
      replay: "Ver de nuevo",
      note: "El cliente publica gratis. El abogado ve el asunto, no el contacto.",
      clientDesk: "Publicando un caso",
      lawyerDesk: "Panel",
      queue: "Enviados ahora",
      emptyQueue: "Nadie ha publicado todavía",
      emptyFeed: "Esperando casos en tu zona",
      drafting: "Escribiendo…",
      posting: "Publicando…",
      posted: "Publicado",
      publish: "Publicar gratis",
      free: "Gratis para el cliente",
      toastTitle: "Nuevo caso",
      hidden: "Contacto reservado",
      cost: "$12",
      online: "En línea",
      fresh: "Nuevo",
      fieldArea: "Asunto",
      fieldCity: "Ciudad",
      clients: [
        {
          name: "Ana M.",
          initials: "AM",
          title: "Asilo — audiencia próxima",
          area: "Inmigración",
          loc: "Houston, TX",
          hidden: "Cliente en Houston",
          lawyer: 0,
        },
        {
          name: "Luis R.",
          initials: "LR",
          title: "DUI — primera comparecencia",
          area: "Penal",
          loc: "Miami, FL",
          hidden: "Cliente en Miami",
          lawyer: 1,
        },
        {
          name: "Carmen S.",
          initials: "CS",
          title: "Residencia — consulta inicial",
          area: "Inmigración",
          loc: "Houston, TX",
          hidden: "Cliente en Houston",
          lawyer: 0,
        },
      ],
      lawyers: [
        { name: "Elena V. Cruz", area: "Inmigración", loc: "Houston, TX" },
        { name: "Michael R. Anderson", area: "Defensa penal", loc: "Miami, FL" },
      ],
    },
    areas: {
      label: "Áreas de práctica",
      title: "Encuentre ayuda según su asunto",
      items: [
        { title: "Inmigración", count: "1,245 asuntos", need: "inmigracion" },
        { title: "Asilo", count: "862 asuntos", need: "asilo" },
        { title: "Familia", count: "734 asuntos", need: "familia" },
        { title: "Penal", count: "518 asuntos", need: "penal" },
        { title: "Laboral", count: "640 asuntos", need: "laboral" },
        { title: "Lesiones", count: "391 asuntos", need: "lesiones" },
      ],
    },
    verify: {
      label: "Verificación",
      title: "Cada abogado del listado ya pasó por esto",
      text: "Licencia de barra, luego Stripe Identity: documento oficial, selfie y prueba de vida. Si falla una, no puede desbloquear tu caso.",
      replay: "Ver de nuevo",
      simLabel: "Revisión",
      desk: "Escritorio de cumplimiento",
      session: "Sesión",
      note: "Licencia estatal, Stripe Identity y doble factor. Sin los tres, no hay desbloqueo.",
      cta: "Verificarme como abogado",
      applicants: [
        {
          name: "Elena V. Cruz",
          role: "Inmigración",
          loc: "Houston, TX",
          barNo: "24081247",
          barState: "TX",
          admitted: "Admitida 12 mar 2014",
          sessionId: "VFY-8F2A-19C4",
          issuer: "State Bar of Texas",
          match: "98.4%",
          dob: "14 mar 1986",
          idNo: "08947261",
          stripeSession: "vs_8F2A19C4",
        },
        {
          name: "Michael R. Anderson",
          role: "Defensa penal",
          loc: "Miami, FL",
          barNo: "1018347",
          barState: "FL",
          admitted: "Admitido 8 jun 2011",
          sessionId: "VFY-3C91-70BE",
          issuer: "The Florida Bar",
          match: "97.6%",
          dob: "2 nov 1983",
          idNo: "A52188493",
          stripeSession: "vs_3C9170BE",
        },
        {
          name: "James P. Whitfield",
          role: "Familia",
          loc: "Indianapolis, IN",
          barNo: "23451-29",
          barState: "IN",
          admitted: "Admitido 3 sep 2008",
          sessionId: "VFY-A14D-55E2",
          issuer: "Indiana State Bar",
          match: "99.1%",
          dob: "19 jul 1979",
          idNo: "234088193",
          stripeSession: "vs_A14D55E2",
        },
        {
          name: "Sofia M. Reyes",
          role: "Asilo",
          loc: "Los Angeles, CA",
          barNo: "2874413",
          barState: "CA",
          admitted: "Admitida 21 ene 2015",
          sessionId: "VFY-6B08-2F91",
          issuer: "State Bar of California",
          match: "98.8%",
          dob: "8 may 1988",
          idNo: "D8472193",
          stripeSession: "vs_6B082F91",
        },
      ],
      stages: [
        { title: "Licencia", hint: "Registro de la barra" },
        { title: "Documento", hint: "ID estatal" },
        { title: "Selfie", hint: "Prueba de vida" },
        { title: "Aprobación", hint: "Listo para el listado" },
      ],
      checks: [
        { title: "Licencia", wait: "Escaneando…", done: "Escaneada" },
        { title: "Documento", wait: "Extrayendo…", done: "document.verified" },
        { title: "Selfie", wait: "Comparando…", done: "selfie.verified" },
        { title: "Aprobación", wait: "Cerrando…", done: "Approved" },
      ],
      ui: {
        querying: "Consultando el registro estatal…",
        match: "Coincidencia",
        liveness: "Prueba de vida",
        enrolled: "Vinculado",
        unlock: "Ya puede desbloquear contactos",
        verified: "Verificado",
        pending: "Pendiente",
        running: "En revisión",
        pass: "Sin sanciones",
        cardTitle: "Licencia de la barra",
        liveCapture: "Selfie",
        totpLabel: "Código del autenticador",
        registry: "Registro estatal",
        discipline: "Disciplina",
        eligible: "Activa · puede ejercer",
        credentialPhoto: "Foto de credencial",
        queue: "Cola 1",
        comparing: "Comparando fotos…",
        barFound: "Licencia encontrada",
        idConfirmed: "Identidad confirmada",
        enteringCode: "Del teléfono del abogado",
        ready: "Listo para el listado",
        checklist: "Lista de revisión",
        scanningLicense: "Escaneando la licencia…",
        licenseIssuer: "State Bar of Texas",
        attorneyTitle: "Attorney at Law",
        faceId: "Face ID",
        continue: "Continuar",
        nextFace: "Abrir selfie",
        nextCode: "Ingresar código",
        nextSeal: "Ver aprobación",
        tapHint: "Toca para continuar",
        approved: "APPROVED",
        verifiedBy: "Verified by D2LE2",
        reading: "Registro estatal",
        found: "Registro confirmado",
        barPortal: "Perfil público de la barra",
        admittedLabel: "Admisión",
        standing: "Good standing",
        disciplineNone: "Sin disciplina pública",
        placeIdFrame: "Coloque el ID en el marco",
        idShot: "ID",
        liveShot: "En vivo",
        resultReady: "Verificación completa",
        checkBar: "Licencia de barra",
        checkId: "Documento oficial",
        checkLive: "Prueba de vida",
        checkMatch: "Coincidencia",
        statusPassed: "Aprobada",
        blinkOnce: "Parpadee una vez",
        lookCamera: "Mire a la cámara",
        holdStill: "Mantenga la mirada",
        captured: "Documento capturado",
        issued: "Emitido",
        issuedDate: "13 ago 2026",
        checksPassed: "Licencia · identidad · prueba de vida",
        liveTag: "EN VIVO",
        certTitle: "Constancia de verificación",
        matchScore: "98.4%",
        compareHint: "Documento vs. selfie",
        refLabel: "Ref.",
        validNote: "Listado activo",
        scanDevice: "Captura de documento",
        rosterHint: "Mismos abogados del directorio",
        nextLawyer: "Siguiente abogado",
        stripe: "Stripe Identity",
        stripePowered: "Powered by Stripe Identity",
        stripeDoc: "Documento",
        stripeSelfie: "Selfie",
        documentVerified: "document.verified",
        selfieVerified: "selfie.verified",
        idType: "ID estatal",
        dobLabel: "Nacimiento",
        nextDoc: "Capturar documento",
        idCapture: "Captura de ID",
        extracting: "Extrayendo datos…",
        report: "VerificationReport",
        stripeNote: "Stripe Identity verifica el documento y la selfie. D2LE2 cruza la licencia.",
        stripeVerify: "Verificar identidad",
        stripeContinue: "Continuar",
        stripeSecure: "Sesión segura",
        stripeOpen: "Abriendo Stripe Identity…",
      },
      licenseReads: [
        { label: "Consulta al registro", done: "Conectado" },
        { label: "Nombre", done: "Elena V. Cruz" },
        { label: "Número de barra", done: "TX 24081247" },
        { label: "Estatus", done: "Activa" },
        { label: "Disciplina pública", done: "Ninguna" },
      ],
      docReads: [
        { label: "Tipo", done: "ID estatal" },
        { label: "Nombre", done: "Elena V. Cruz" },
        { label: "Nacimiento", done: "14 mar 1986" },
        { label: "Número de ID", done: "08947261" },
        { label: "Documento", done: "Verificado" },
      ],
      selfieReads: [
        { label: "Selfie", done: "Capturada" },
        { label: "Prueba de vida", done: "Confirmada" },
        { label: "Foto vs. documento", done: "98.4%" },
        { label: "Identidad", done: "Confirmada" },
      ],
      items: [
        { title: "Licencia estatal", text: "Número de barra y estado, revisados antes de operar." },
        { title: "Stripe Identity", text: "Documento oficial, selfie y prueba de vida. Si no coincide, no entra." },
        { title: "Doble factor", text: "En producción, el abogado entra al listado con autenticación de dos pasos." },
        { title: "Contacto reservado", text: "Nombre, correo y teléfono no viajan en el feed." },
      ],
    },
    live: {
      label: "En tiempo real",
      title: "Casos que necesitan ayuda ahora",
      text: "Así se ve el listado. El asunto sí. El nombre y el teléfono, no.",
      hidden: "Contacto reservado",
      cta: "Publicar mi caso gratis",
      items: [
        { title: "Residencia — consulta inicial", area: "Inmigración", loc: "Miami, FL", time: "Hace 2 min" },
        { title: "Asilo — audiencia próxima", area: "Inmigración", loc: "Houston, TX", time: "Hace 8 min" },
        { title: "Custodia — modificación", area: "Familia", loc: "Los Angeles, CA", time: "Hace 14 min" },
        { title: "DUI — primera comparecencia", area: "Penal", loc: "Orlando, FL", time: "Hace 21 min" },
      ],
    },
    match: {
      label: "Así se conectan",
      title: "Del caso anónimo al primer mensaje",
      text: "El cliente publica gratis. El abogado cubre el contacto. 72 horas exclusivas. Nombre y teléfono no aparecen en el listado hasta el desbloqueo.",
      replay: "Ver de nuevo",
      note: "El cliente no paga. El contacto se revela al desbloquear. Si el abogado rechaza o se vence el plazo, el caso vuelve al listado sin reembolso.",
      ctaClient: "Publicar mi caso gratis",
      ctaLawyer: "Ver casos como abogado",
      clientRole: "Cliente",
      lawyerRole: "Abogado",
      stages: [
        { title: "Publicado", hint: "En el listado, sin nombre" },
        { title: "Desbloqueo", hint: "El abogado cubre el contacto" },
        { title: "Reservado", hint: "72 horas exclusivas" },
        { title: "Conversación", hint: "Ya pueden hablar" },
      ],
      case: {
        title: "Asilo — audiencia en 12 días",
        area: "Inmigración",
        loc: "Houston, TX",
        id: "Caso 2418",
        cost: "$12",
        detail: "Aviso de corte. Español. Primera consulta.",
        unlockUsd: "$12",
        earnUsd: "$1,500",
      },
      client: {
        name: "Ana M. Morales",
        hidden: "Cliente en Houston",
        phone: "(713) 555-4182",
        phoneHidden: "Teléfono reservado",
        email: "ana.m@correo.com",
        emailHidden: "Correo reservado",
        initials: "AM",
      },
      lawyer: {
        name: "Elena V. Cruz",
        area: "Inmigración",
        loc: "Houston, TX",
        wallet: "48",
        walletAfter: "36",
        debit: "−12",
      },
      ui: {
        posting: "Enviando tu caso…",
        drafting: "Escribiendo el expediente…",
        posted: "Tu caso ya está publicado",
        waiting: "Buscando un abogado verificado",
        emptyDesk: "El listado está en silencio",
        arrived: "Nuevo caso en tu escritorio",
        readingCase: "Leyendo el expediente…",
        reviewing: "Un abogado verificado está revisando tu caso. Tienes 72 horas reservadas.",
        held: "Reservado 72 horas",
        matched: "Ya están en contacto",
        available: "Nuevo",
        unlock: "Desbloquear contacto",
        unlocking: "Desbloqueando…",
        unlockedDone: "Contacto desbloqueado",
        accept: "Aceptar este caso",
        accepting: "Confirmando…",
        debitNote: "12 créditos · $12",
        unlockUsdLabel: "Desbloquear contacto",
        earnUsdLabel: "Honorario estimado",
        earnHint: "Tú facturas al cliente. La plataforma solo cobra el contacto.",
        spentNote: "Pagaste $12 por el contacto",
        acceptReceipt: "Caso en tu práctica · 72 h exclusivas",
        feed: "Tus casos",
        wallet: "créditos",
        exclusive: "Reservado",
        reveal: "Contacto disponible",
        typing: "escribiendo…",
        free: "Sin costo para ti",
        noPii: "El nombre y el teléfono se muestran al desbloquear",
        online: "Activa",
        lead: "Caso",
        myCase: "Mi caso",
        cases: "Casos",
      },
      thread: [
        { from: "client" as const, text: "Gracias por aceptar. La audiencia es el 25.", time: "10:41" },
        { from: "lawyer" as const, text: "La reviso hoy. ¿Tiene el notice de la corte?", time: "10:41" },
        { from: "client" as const, text: "Sí. Lo subo ahora.", time: "10:42" },
      ],
    },
    lawyers: {
      label: "Directorio",
      title: "Abogados verificados",
      text: "Licencia e identidad confirmadas. El cliente no paga por el contacto.",
      cta: "Ver directorio",
      profile: "Ver perfil",
      reviews: "reseñas",
      items: [
        { name: "Elena V. Cruz", area: "Inmigración", loc: "Houston, TX", years: "12 años", rating: "4.9", reviews: "214" },
        { name: "Michael R. Anderson", area: "Defensa penal", loc: "Miami, FL", years: "15 años", rating: "4.9", reviews: "127" },
        { name: "James P. Whitfield", area: "Familia", loc: "Indianapolis, IN", years: "18 años", rating: "4.8", reviews: "86" },
        { name: "Sofia M. Reyes", area: "Asilo", loc: "Los Angeles, CA", years: "11 años", rating: "4.9", reviews: "141" },
      ],
    },
    benefits: {
      title: "Usted publica.",
      titleLine2: "Ellos responden.",
      text: "El cliente cuenta el caso. El abogado verificado se acerca. Usted no paga por usar la plataforma.",
      items: [
        {
          title: "Publique gratis",
          text: "Cuente su situación en minutos. El cliente nunca paga.",
        },
        {
          title: "Sus datos reservados",
          text: "Nombre y teléfono no aparecen hasta que un abogado asuma el caso.",
        },
        {
          title: "Abogados verificados",
          text: "Licencia, identidad y doble factor antes de ver su contacto.",
        },
        {
          title: "Usted elige",
          text: "Converse y decida con quién seguir. Sin presión.",
        },
      ],
      partnersLabel: "Con la confianza de",
      partnersUsa: "Abogados de todo USA",
      partners: ["Lawyers.com", "Avvo", "Martindale-Hubbell", "Justia"],
    },
    pricing: {
      label: "Precios",
      title: "Cliente gratis. Abogado paga por lead.",
      plans: [
        {
          name: "Cliente",
          price: "$0",
          note: "siempre gratis",
          features: [
            "Crear caso sin costo",
            "Matching con profesionales",
            "Soporte ES / EN",
          ],
          cta: "Iniciar mi caso",
          featured: false,
          role: "client" as const,
        },
        {
          name: "Abogado",
          price: "Créditos",
          note: "paga solo al desbloquear",
          features: [
            "Perfil verificado",
            "Feed de leads en tiempo real",
            "Pay-per-lead sin cuota fija",
            "Soporte 24/7 bilingüe",
          ],
          cta: "Registro profesional",
          featured: true,
          role: "lawyer" as const,
        },
        {
          name: "Firma",
          price: "A medida",
          note: "equipos y bufetes",
          features: [
            "Múltiples abogados",
            "Billetera compartida",
            "Gerente de cuenta",
            "Integraciones",
          ],
          cta: "Hablar con ventas",
          featured: false,
          role: "lawyer" as const,
        },
      ],
      popular: "Popular",
    },
    resources: {
      label: "Recursos",
      title: "Para entender su caso",
      download: "Leer →",
      items: [
        { tag: "Guía", title: "Qué llevar a una audiencia de asilo" },
        { tag: "Lista", title: "Documentos para pedir residencia familiar" },
        { tag: "Pasos", title: "Cómo publicar su caso sin costo" },
      ],
    },
    register: {
      label: "Registro",
      title: "Cree su cuenta según su rol",
      text: "El cliente publica el caso. El abogado se verifica para operar. Son dos registros distintos.",
      back: "Cambiar rol",
      home: "Volver al inicio",
      doneTitle: "Solicitud recibida",
      doneClient: "Recibimos su registro. Un asesor le escribirá para abrir el caso. Publicar no crea relación abogado-cliente.",
      doneLawyer: "Recibimos su registro profesional. Revisaremos licencia e identidad antes de darle acceso al contacto.",
      disclaimer:
        "D2LE2 Law no es un bufete. El registro no crea relación abogado-cliente. El abogado no ve nombre ni teléfono hasta desbloquear.",
      submitClient: "Crear cuenta de cliente",
      submitLawyer: "Crear cuenta de abogado",
      zipNote: "Buscando cerca del ZIP {zip}.",
      needPrefill: {
        asilo: "Necesito ayuda con una audiencia de asilo.",
        residencia: "Quiero pedir residencia para mi familia.",
        familia: "Necesito ayuda con un asunto de familia.",
        penal: "Tengo una cita en corte y necesito un abogado.",
        laboral: "Tengo un problema laboral y busco orientación.",
        lesiones: "Sufrí una lesión y necesito orientación legal.",
        inmigracion: "Necesito ayuda con un trámite de inmigración.",
        apelacion: "Me negaron un trámite y quiero entender opciones.",
        otro: "Quiero contar mi situación y que me contacte un abogado verificado.",
      },
      clientCard: {
        title: "Soy cliente",
        text: "Publique su caso sin costo. Los abogados lo ven sin sus datos de contacto.",
        cta: "Registrar como cliente",
      },
      lawyerCard: {
        title: "Soy abogado",
        text: "Licencia e identidad. Luego el feed, créditos y el hold de 72 horas.",
        cta: "Registro profesional",
      },
      clientFields: [
        { label: "Nombre", ph: "Nombre y apellido", type: "text" },
        { label: "Correo", ph: "tu@correo.com", type: "email" },
        { label: "Teléfono", ph: "(305) 000-0000", type: "tel" },
        { label: "Estado", ph: "Florida", type: "text" },
        { label: "Describa su caso", ph: "Qué ocurrió y qué necesita", type: "text", multiline: true, wide: true },
      ],
      lawyerFields: [
        { label: "Nombre legal", ph: "Como aparece en la barra", type: "text" },
        { label: "Correo profesional", ph: "tu@bufete.com", type: "email" },
        { label: "Teléfono", ph: "(305) 000-0000", type: "tel" },
        { label: "Estado de licencia", ph: "Florida", type: "text" },
        { label: "Número de barra", ph: "FL-123456", type: "text" },
        { label: "Área de práctica", ph: "Inmigración", type: "text" },
      ],
    },
    contact: {
      label: "Contacto",
      title: "¿Tiene una pregunta?",
      text: "Soporte bilingüe 24/7. Esto no abre una cuenta. El registro está en una página aparte.",
      submit: "Enviar mensaje",
      done: "Mensaje enviado. Le responderemos a la brevedad.",
      fields: {
        name: "Nombre",
        namePh: "Nombre y apellido",
        email: "Correo",
        emailPh: "tu@correo.com",
        phone: "Teléfono",
        phonePh: "(305) 000-0000",
        message: "Mensaje",
        messagePh: "¿En qué podemos ayudarle?",
      },
    },
    footer: {
      blurb:
        "Marketplace legal bilingüe que conecta clientes con abogados verificados. Cliente gratis. Abogados pagan por lead.",
      cols: [
        {
          title: "Plataforma",
          links: [
            { label: "Cómo funciona", href: "#como-funciona" },
            { label: "Áreas", href: "#areas" },
            { label: "Verificación", href: "#verificacion" },
            { label: "Precios", href: "#precios" },
          ],
        },
        {
          title: "Legal",
          links: [
            { label: "Aviso legal", href: "#aviso-legal" },
            { label: "Contacto", href: "#contacto" },
            { label: "Recursos", href: "#recursos" },
          ],
        },
      ],
      disclaimer:
        "D2LE2 Law es un marketplace tecnológico. No prestamos asesoría legal ni somos un bufete. No establecemos relación abogado-cliente.",
      copyright: "D2LE2 Law. Marketplace legal. Todos los derechos reservados.",
    },
    chat: {
      online: "En línea",
      lawyersOnline: "abogados en línea",
      availableNow: "Available now",
      minimize: "Minimizar chat",
      open: "Abrir chat",
      close: "Cerrar chat",
      placeholder: "Escribe tu mensaje...",
      attach: "Adjuntar",
      send: "Enviar mensaje",
      messages: [
        {
          from: "bot" as const,
          text: "¡Hola! ¿Eres cliente buscando ayuda o abogado buscando leads?",
          time: "10:30 AM",
        },
        {
          from: "me" as const,
          text: "Quiero saber cómo funciona la plataforma.",
          time: "10:31 AM",
        },
        {
          from: "bot" as const,
          text: "Los clientes inician su caso gratis. Los abogados revisan leads anonimizados y pagan solo al desbloquear el contacto.",
          time: "10:32 AM",
        },
      ],
    },
    phone: "(305) 987-0000",
    phoneHref: "tel:+13059870000",
  },
  en: {
    meta: {
      title: "D2LE2 Law — Bilingual legal marketplace",
      description:
        "Immigration help and qualified leads in one place. Free for clients. Lawyers pay only to unlock. Technology marketplace — we are not a law firm.",
      ogTitle: "D2LE2 Law — Bilingual legal marketplace",
      ogDescription:
        "Choose your path: start your case or get live leads as an attorney.",
    },
    header: {
      ticker: [
        "Available 24/7",
        "Free for clients",
        "Contact hidden until unlock",
        "Pay-per-lead for lawyers",
        "72-hour exclusive hold",
      ],
      speakLang: "We speak Spanish",
      nav: [
        { label: "Home", href: "#inicio" },
        { label: "How it works", href: "#como-funciona" },
        { label: "Verification", href: "#verificacion" },
        { label: "Areas", href: "#areas" },
        { label: "Lawyers", href: "#abogados" },
        { label: "Connection", href: "#casos" },
        { label: "Benefits", href: "#beneficios", children: true },
        { label: "Pricing", href: "#precios" },
        { label: "Resources", href: "#recursos" },
        { label: "Sign up", href: "/registro" },
        { label: "Contact", href: "#contacto" },
      ],
      benefitLinks: [
        { label: "Real clients", href: "#beneficios" },
        { label: "Live dashboard", href: "#panel" },
        { label: "Bilingual support", href: "#soporte" },
      ],
      phoneSub: "Available 24/7",
      ctaClient: "I'm a client",
      ctaLawyer: "I'm a lawyer",
      dockChat: "Chat",
      dockCall: "Call",
      menuOpen: "Open menu",
      langEs: "ES",
      langEn: "EN",
    },
    hero: {
      label: "Free for you · Verified lawyers",
      title: "Immigration help for your family,",
      titleAccent: "in one place.",
      subtitle:
        "Tell us your situation in minutes. You don't pay. D2LE2 Law is not a law firm and does not give legal advice.",
      clientCta: "I'm a client — start case",
      lawyerCta: "I'm a lawyer — free signup",
      callCta: "Call now 24/7",
      zipLabel: "ZIP code",
      zipPlaceholder: "ZIP code",
      zipSearch: "Search",
      zipHint: "Free. Verified lawyers near you.",
      zipError: "Enter a 5-digit ZIP.",
      needPrompt: "What do you need help with?",
      needs: [
        { need: "asilo", label: "Asylum" },
        { need: "residencia", label: "Green card" },
        { need: "familia", label: "Family" },
        { need: "penal", label: "Court" },
        { need: "laboral", label: "Work" },
        { need: "otro", label: "Something else" },
      ],
      onlineClients: "clients online",
      onlinePros: "professionals online",
      ratingLabel: "Trustpilot",
      ratingScore: "4.9",
      ratingCount: "| 2,500+ Reviews",
      stats: [
        { value: 15000, prefix: "+", suffix: "", label: "Clients connected", labelShort: "Clients\nconnected" },
        { value: 2500, prefix: "+", suffix: "", label: "Active lawyers", labelShort: "Active\nlawyers" },
        { value: 98, prefix: "", suffix: "%", label: "Satisfaction", labelShort: "Success\nrate" },
        { value: 20, prefix: "", suffix: "+", label: "Practice areas", labelShort: "Practice\nareas" },
      ],
      imageAlt: "Empty courthouse interior, with no people",
    },
    trust: {
      tagline: "You tell your case. We make the connection.",
      items: [
        { lines: ["100% free", "for you"] },
        { lines: ["Your details", "stay reserved"] },
        { lines: ["Verified", "lawyers"] },
        { lines: ["We speak", "your language"] },
        { lines: ["No pressure", "no commitment"] },
      ],
    },
    need: {
      id: "su-caso",
      label: "Your case",
      title: "Do you recognize yourself in any of these?",
      text: "Tap the one that sounds like yours. It's free, and your phone stays hidden for now.",
      cta: "This is my situation",
      items: [
        {
          need: "asilo",
          title: "I have an asylum hearing",
          text: "I don't know what to bring or who to ask.",
        },
        {
          need: "residencia",
          title: "I want a green card for my family",
          text: "Spouse, children, or parents. I need to start right.",
        },
        {
          need: "penal",
          title: "I have a court date",
          text: "I was arrested or cited. I need to talk to a lawyer.",
        },
        {
          need: "apelacion",
          title: "My application was denied",
          text: "I want options from someone verified.",
        },
      ],
    },
    audience: {
      id: "caminos",
      clientLabel: "For clients",
      clientTitle: "You don't pay. They come to you.",
      clientSub:
        "Immigration and more US legal areas. Tell your case. Verified lawyers see it without your name. Free for you.",
      clientCta: "Start my case",
      clientCards: [
        { title: "Describe your case", text: "Tell us what you need in minutes." },
        { title: "Fast matching", text: "Verified lawyers see the matter — not your name or phone." },
        { title: "100% free", text: "Clients never pay to use the platform." },
        { title: "Secure & private", text: "Posting does not create an attorney-client relationship." },
      ],
      lawyerLabel: "For lawyers",
      lawyerTitle: "More clients. More control.",
      lawyerSub:
        "Get qualified leads, review anonymized cases, and unlock only the ones you want.",
      lawyerCta: "Create professional account",
      lawyerCards: [
        { title: "Live leads", text: "Immigration and legal clients in real time." },
        { title: "You decide", text: "72-hour exclusive hold. Up to three matters at once." },
        { title: "Pay-per-lead", text: "Pay only to unlock. No refund if you reject or time out." },
        { title: "Pro dashboard", text: "Feed, wallet, and dedicated support." },
      ],
    },
    how: {
      label: "How it works",
      title: "Three steps. You don't pay.",
      tabClient: "Client",
      tabLawyer: "Lawyer",
      clientSteps: [
        {
          n: "01",
          title: "Describe your case",
          text: "Tell us your immigration or legal situation in plain language.",
        },
        {
          n: "02",
          title: "They see it without your data",
          text: "The feed shows the matter and jurisdiction. Name and phone stay reserved.",
        },
        {
          n: "03",
          title: "You choose",
          text: "Talk and decide who continues. Contact is revealed if a lawyer takes the case.",
        },
      ],
      lawyerSteps: [
        {
          n: "01",
          title: "Get verified",
          text: "State bar license and identity. Without both, there is no contact access.",
        },
        {
          n: "02",
          title: "Review live leads",
          text: "Filter by state and area. The client stays anonymous until unlock.",
        },
        {
          n: "03",
          title: "Unlock for 72 hours",
          text: "The charge is not refunded. If you accept, you talk with full contact data.",
        },
      ],
      panels: [
        {
          t: "You post",
          d: "Tell the matter in minutes. It stays free.",
        },
        {
          t: "Without your name",
          d: "The feed shows the case, not your phone.",
        },
        {
          t: "You decide",
          d: "Talk when a verified lawyer takes the contact.",
        },
      ],
    },
    pulse: {
      id: "en-vivo",
      label: "Live now",
      title: "Clients walk in. The desk lights up.",
      text: "Each case lands anonymized on the right lawyer’s desk. Name and phone stay reserved until unlock.",
      replay: "Watch again",
      note: "The client posts for free. The lawyer sees the matter, not the contact.",
      clientDesk: "Posting a case",
      lawyerDesk: "Desk",
      queue: "Just posted",
      emptyQueue: "No one has posted yet",
      emptyFeed: "Waiting for cases in your area",
      drafting: "Writing…",
      posting: "Posting…",
      posted: "Posted",
      publish: "Post for free",
      free: "Free for the client",
      toastTitle: "New case",
      hidden: "Contact reserved",
      cost: "$12",
      online: "Online",
      fresh: "New",
      fieldArea: "Matter",
      fieldCity: "City",
      clients: [
        {
          name: "Ana M.",
          initials: "AM",
          title: "Asylum — upcoming hearing",
          area: "Immigration",
          loc: "Houston, TX",
          hidden: "Client in Houston",
          lawyer: 0,
        },
        {
          name: "Luis R.",
          initials: "LR",
          title: "DUI — first appearance",
          area: "Criminal",
          loc: "Miami, FL",
          hidden: "Client in Miami",
          lawyer: 1,
        },
        {
          name: "Carmen S.",
          initials: "CS",
          title: "Residency — first consult",
          area: "Immigration",
          loc: "Houston, TX",
          hidden: "Client in Houston",
          lawyer: 0,
        },
      ],
      lawyers: [
        { name: "Elena V. Cruz", area: "Immigration", loc: "Houston, TX" },
        { name: "Michael R. Anderson", area: "Criminal defense", loc: "Miami, FL" },
      ],
    },
    areas: {
      label: "Practice areas",
      title: "Find help for your matter",
      items: [
        { title: "Immigration", count: "1,245 matters", need: "inmigracion" },
        { title: "Asylum", count: "862 matters", need: "asilo" },
        { title: "Family", count: "734 matters", need: "familia" },
        { title: "Criminal", count: "518 matters", need: "penal" },
        { title: "Employment", count: "640 matters", need: "laboral" },
        { title: "Injury", count: "391 matters", need: "lesiones" },
      ],
    },
    verify: {
      label: "Verification",
      title: "Every lawyer in the feed already passed this",
      text: "Bar license, then Stripe Identity: government ID, selfie, and liveness. If one check fails, they cannot unlock your case.",
      replay: "Watch again",
      simLabel: "Review",
      desk: "Compliance desk",
      session: "Session",
      note: "State license, Stripe Identity, and two-factor. Without all three, there is no unlock.",
      cta: "Get verified as a lawyer",
      applicants: [
        {
          name: "Elena V. Cruz",
          role: "Immigration",
          loc: "Houston, TX",
          barNo: "24081247",
          barState: "TX",
          admitted: "Admitted Mar 12, 2014",
          sessionId: "VFY-8F2A-19C4",
          issuer: "State Bar of Texas",
          match: "98.4%",
          dob: "Mar 14, 1986",
          idNo: "08947261",
          stripeSession: "vs_8F2A19C4",
        },
        {
          name: "Michael R. Anderson",
          role: "Criminal defense",
          loc: "Miami, FL",
          barNo: "1018347",
          barState: "FL",
          admitted: "Admitted Jun 8, 2011",
          sessionId: "VFY-3C91-70BE",
          issuer: "The Florida Bar",
          match: "97.6%",
          dob: "Nov 2, 1983",
          idNo: "A52188493",
          stripeSession: "vs_3C9170BE",
        },
        {
          name: "James P. Whitfield",
          role: "Family law",
          loc: "Indianapolis, IN",
          barNo: "23451-29",
          barState: "IN",
          admitted: "Admitted Sep 3, 2008",
          sessionId: "VFY-A14D-55E2",
          issuer: "Indiana State Bar",
          match: "99.1%",
          dob: "Jul 19, 1979",
          idNo: "234088193",
          stripeSession: "vs_A14D55E2",
        },
        {
          name: "Sofia M. Reyes",
          role: "Asylum",
          loc: "Los Angeles, CA",
          barNo: "2874413",
          barState: "CA",
          admitted: "Admitted Jan 21, 2015",
          sessionId: "VFY-6B08-2F91",
          issuer: "State Bar of California",
          match: "98.8%",
          dob: "May 8, 1988",
          idNo: "D8472193",
          stripeSession: "vs_6B082F91",
        },
      ],
      stages: [
        { title: "License", hint: "Bar registry" },
        { title: "Document", hint: "State ID" },
        { title: "Selfie", hint: "Liveness check" },
        { title: "Approval", hint: "Ready for the directory" },
      ],
      checks: [
        { title: "License", wait: "Scanning…", done: "Scanned" },
        { title: "Document", wait: "Extracting…", done: "document.verified" },
        { title: "Selfie", wait: "Comparing…", done: "selfie.verified" },
        { title: "Approval", wait: "Closing…", done: "Approved" },
      ],
      ui: {
        querying: "Checking the state registry…",
        match: "Match",
        liveness: "Liveness",
        enrolled: "Linked",
        unlock: "Can unlock contacts",
        verified: "Verified",
        pending: "Pending",
        running: "In review",
        pass: "No sanctions",
        cardTitle: "Bar license",
        liveCapture: "Selfie",
        totpLabel: "Authenticator code",
        registry: "State registry",
        discipline: "Discipline",
        eligible: "Active · may practice",
        credentialPhoto: "Credential photo",
        queue: "Queue 1",
        comparing: "Comparing photos…",
        barFound: "License found",
        idConfirmed: "Identity confirmed",
        enteringCode: "From the lawyer’s phone",
        ready: "Ready for the directory",
        checklist: "Review list",
        scanningLicense: "Scanning the license…",
        licenseIssuer: "State Bar of Texas",
        attorneyTitle: "Attorney at Law",
        faceId: "Face ID",
        continue: "Continue",
        nextFace: "Open selfie",
        nextCode: "Enter the code",
        nextSeal: "See approval",
        tapHint: "Tap to continue",
        approved: "APPROVED",
        verifiedBy: "Verified by D2LE2",
        reading: "State registry",
        found: "Registry confirmed",
        barPortal: "Public attorney profile",
        admittedLabel: "Admitted",
        standing: "Good standing",
        disciplineNone: "No public discipline",
        placeIdFrame: "Place your ID in the frame",
        idShot: "ID",
        liveShot: "Live",
        resultReady: "Verification complete",
        checkBar: "Bar license",
        checkId: "Government ID",
        checkLive: "Liveness",
        checkMatch: "Match",
        statusPassed: "Passed",
        blinkOnce: "Blink once",
        lookCamera: "Look at the camera",
        holdStill: "Hold still",
        captured: "Document captured",
        issued: "Issued",
        issuedDate: "Aug 13, 2026",
        checksPassed: "License · identity · liveness",
        liveTag: "LIVE",
        certTitle: "Verification certificate",
        matchScore: "98.4%",
        compareHint: "Document vs. selfie",
        refLabel: "Ref.",
        validNote: "Active listing",
        scanDevice: "Document capture",
        rosterHint: "Same lawyers as the directory",
        nextLawyer: "Next lawyer",
        stripe: "Stripe Identity",
        stripePowered: "Powered by Stripe Identity",
        stripeDoc: "Document",
        stripeSelfie: "Selfie",
        documentVerified: "document.verified",
        selfieVerified: "selfie.verified",
        idType: "State ID",
        dobLabel: "Date of birth",
        nextDoc: "Capture document",
        idCapture: "ID capture",
        extracting: "Extracting data…",
        report: "VerificationReport",
        stripeNote: "Stripe Identity verifies the document and selfie. D2LE2 checks the bar license.",
        stripeVerify: "Verify your identity",
        stripeContinue: "Continue",
        stripeSecure: "Secure session",
        stripeOpen: "Opening Stripe Identity…",
      },
      licenseReads: [
        { label: "Registry query", done: "Connected" },
        { label: "Name", done: "Elena V. Cruz" },
        { label: "Bar number", done: "TX 24081247" },
        { label: "Status", done: "Active" },
        { label: "Public discipline", done: "None" },
      ],
      docReads: [
        { label: "Type", done: "State ID" },
        { label: "Name", done: "Elena V. Cruz" },
        { label: "Date of birth", done: "Mar 14, 1986" },
        { label: "ID number", done: "08947261" },
        { label: "Document", done: "Verified" },
      ],
      selfieReads: [
        { label: "Selfie", done: "Captured" },
        { label: "Liveness", done: "Confirmed" },
        { label: "Photo vs. document", done: "98.4%" },
        { label: "Identity", done: "Confirmed" },
      ],
      items: [
        { title: "State license", text: "Bar number and state, reviewed before operating." },
        { title: "Stripe Identity", text: "Government ID, selfie, and liveness. If they do not match, no access." },
        { title: "Two-factor", text: "In production, lawyers enter the feed only with 2FA." },
        { title: "Reserved contact", text: "Name, email, and phone never travel in the feed." },
      ],
    },
    live: {
      label: "Live now",
      title: "Cases that need help now",
      text: "This is the list. The matter shows. Name and phone do not.",
      hidden: "Contact reserved",
      cta: "Post my case for free",
      items: [
        { title: "Residency — first consult", area: "Immigration", loc: "Miami, FL", time: "2 min ago" },
        { title: "Asylum — upcoming hearing", area: "Immigration", loc: "Houston, TX", time: "8 min ago" },
        { title: "Custody — modification", area: "Family", loc: "Los Angeles, CA", time: "14 min ago" },
        { title: "DUI — first appearance", area: "Criminal", loc: "Orlando, FL", time: "21 min ago" },
      ],
    },
    match: {
      label: "How they connect",
      title: "From an anonymous case to the first message",
      text: "The client posts for free. The lawyer covers the contact. 72 hours exclusive. Name and phone do not appear in the list until unlock.",
      replay: "Watch again",
      note: "The client never pays. Contact is revealed at unlock. If the lawyer declines or the window ends, the case returns to the list with no refund.",
      ctaClient: "Post my case for free",
      ctaLawyer: "See cases as a lawyer",
      clientRole: "Client",
      lawyerRole: "Lawyer",
      stages: [
        { title: "Posted", hint: "On the list, no name" },
        { title: "Unlock", hint: "The lawyer covers contact" },
        { title: "Reserved", hint: "72 hours exclusive" },
        { title: "Conversation", hint: "They can talk now" },
      ],
      case: {
        title: "Asylum — hearing in 12 days",
        area: "Immigration",
        loc: "Houston, TX",
        id: "Case 2418",
        cost: "$12",
        detail: "Court notice. Spanish. First consult.",
        unlockUsd: "$12",
        earnUsd: "$1,500",
      },
      client: {
        name: "Ana M. Morales",
        hidden: "Client in Houston",
        phone: "(713) 555-4182",
        phoneHidden: "Phone reserved",
        email: "ana.m@correo.com",
        emailHidden: "Email reserved",
        initials: "AM",
      },
      lawyer: {
        name: "Elena V. Cruz",
        area: "Immigration",
        loc: "Houston, TX",
        wallet: "48",
        walletAfter: "36",
        debit: "−12",
      },
      ui: {
        posting: "Sending your case…",
        drafting: "Writing the case file…",
        posted: "Your case is posted",
        waiting: "Looking for a verified lawyer",
        emptyDesk: "The list is quiet",
        arrived: "New case on your desk",
        readingCase: "Reading the file…",
        reviewing: "A verified lawyer is reviewing your case. You have 72 hours reserved.",
        held: "Reserved for 72 hours",
        matched: "You’re in contact",
        available: "New",
        unlock: "Unlock contact",
        unlocking: "Unlocking…",
        unlockedDone: "Contact unlocked",
        accept: "Accept this case",
        accepting: "Confirming…",
        debitNote: "12 credits · $12",
        unlockUsdLabel: "Unlock contact",
        earnUsdLabel: "Estimated fee",
        earnHint: "You bill the client. The platform only charges for contact.",
        spentNote: "You paid $12 for the contact",
        acceptReceipt: "Case on your desk · 72h exclusive",
        feed: "Your cases",
        wallet: "credits",
        exclusive: "Reserved",
        reveal: "Contact available",
        typing: "typing…",
        free: "No cost to you",
        noPii: "Name and phone appear after unlock",
        online: "Active",
        lead: "Case",
        myCase: "My case",
        cases: "Cases",
      },
      thread: [
        { from: "client" as const, text: "Thanks for taking this. The hearing is on the 25th.", time: "10:41" },
        { from: "lawyer" as const, text: "I’ll review it today. Do you have the court notice?", time: "10:41" },
        { from: "client" as const, text: "Yes. Uploading it now.", time: "10:42" },
      ],
    },
    lawyers: {
      label: "Directory",
      title: "Verified lawyers",
      text: "License and identity confirmed. Clients never pay for the contact.",
      cta: "View directory",
      profile: "View profile",
      reviews: "reviews",
      items: [
        { name: "Elena V. Cruz", area: "Immigration", loc: "Houston, TX", years: "12 years", rating: "4.9", reviews: "214" },
        { name: "Michael R. Anderson", area: "Criminal defense", loc: "Miami, FL", years: "15 years", rating: "4.9", reviews: "127" },
        { name: "James P. Whitfield", area: "Family law", loc: "Indianapolis, IN", years: "18 years", rating: "4.8", reviews: "86" },
        { name: "Sofia M. Reyes", area: "Asylum", loc: "Los Angeles, CA", years: "11 years", rating: "4.9", reviews: "141" },
      ],
    },
    benefits: {
      title: "You post.",
      titleLine2: "They respond.",
      text: "The client tells the case. A verified lawyer comes forward. You don't pay to use the platform.",
      items: [
        {
          title: "Post for free",
          text: "Tell your situation in minutes. Clients never pay.",
        },
        {
          title: "Your details reserved",
          text: "Name and phone stay hidden until a lawyer takes the case.",
        },
        {
          title: "Verified lawyers",
          text: "License, identity, and two-factor before they see your contact.",
        },
        {
          title: "You choose",
          text: "Talk and decide who continues. No pressure.",
        },
      ],
      partnersLabel: "Trusted by",
      partnersUsa: "Attorneys across the USA",
      partners: ["Lawyers.com", "Avvo", "Martindale-Hubbell", "Justia"],
    },
    pricing: {
      label: "Pricing",
      title: "Free for clients. Lawyers pay per lead.",
      plans: [
        {
          name: "Client",
          price: "$0",
          note: "always free",
          features: [
            "Create a case at no cost",
            "Match with professionals",
            "ES / EN support",
          ],
          cta: "Start my case",
          featured: false,
          role: "client" as const,
        },
        {
          name: "Lawyer",
          price: "Credits",
          note: "pay only to unlock",
          features: [
            "Verified profile",
            "Live lead feed",
            "Pay-per-lead, no fixed fee",
            "24/7 bilingual support",
          ],
          cta: "Professional signup",
          featured: true,
          role: "lawyer" as const,
        },
        {
          name: "Firm",
          price: "Custom",
          note: "teams and firms",
          features: [
            "Multiple attorneys",
            "Shared wallet",
            "Account manager",
            "Integrations",
          ],
          cta: "Talk to sales",
          featured: false,
          role: "lawyer" as const,
        },
      ],
      popular: "Popular",
    },
    resources: {
      label: "Resources",
      title: "To understand your case",
      download: "Read →",
      items: [
        { tag: "Guide", title: "What to bring to an asylum hearing" },
        { tag: "List", title: "Documents for a family green card" },
        { tag: "Steps", title: "How to post your case at no cost" },
      ],
    },
    register: {
      label: "Sign up",
      title: "Create the account that matches your role",
      text: "Clients post a case. Lawyers verify to operate. Two different registrations.",
      back: "Change role",
      home: "Back to home",
      doneTitle: "Request received",
      doneClient: "We received your signup. An advisor will write to open the case. Posting does not create an attorney-client relationship.",
      doneLawyer: "We received your professional signup. We will review license and identity before contact access.",
      disclaimer:
        "D2LE2 Law is not a law firm. Signup does not create an attorney-client relationship. Lawyers do not see name or phone until unlock.",
      submitClient: "Create client account",
      submitLawyer: "Create lawyer account",
      zipNote: "Looking near ZIP {zip}.",
      needPrefill: {
        asilo: "I need help with an asylum hearing.",
        residencia: "I want to apply for a family green card.",
        familia: "I need help with a family matter.",
        penal: "I have a court date and need a lawyer.",
        laboral: "I have a work issue and need guidance.",
        lesiones: "I was injured and need legal guidance.",
        inmigracion: "I need help with an immigration filing.",
        apelacion: "My application was denied and I want options.",
        otro: "I want to explain my situation and hear from a verified lawyer.",
      },
      clientCard: {
        title: "I am a client",
        text: "Post your case at no cost. Lawyers see the matter without your contact details.",
        cta: "Register as a client",
      },
      lawyerCard: {
        title: "I am a lawyer",
        text: "License and identity first. Then the feed, credits, and the 72-hour hold.",
        cta: "Professional signup",
      },
      clientFields: [
        { label: "Name", ph: "Full name", type: "text" },
        { label: "Email", ph: "you@email.com", type: "email" },
        { label: "Phone", ph: "(305) 000-0000", type: "tel" },
        { label: "State", ph: "Florida", type: "text" },
        { label: "Describe your case", ph: "What happened and what you need", type: "text", multiline: true, wide: true },
      ],
      lawyerFields: [
        { label: "Legal name", ph: "As it appears on the bar", type: "text" },
        { label: "Professional email", ph: "you@firm.com", type: "email" },
        { label: "Phone", ph: "(305) 000-0000", type: "tel" },
        { label: "License state", ph: "Florida", type: "text" },
        { label: "Bar number", ph: "FL-123456", type: "text" },
        { label: "Practice area", ph: "Immigration", type: "text" },
      ],
    },
    contact: {
      label: "Contact",
      title: "Have a question?",
      text: "Bilingual support 24/7. This does not create an account. Sign up lives on its own page.",
      submit: "Send message",
      done: "Message sent. We will reply shortly.",
      fields: {
        name: "Name",
        namePh: "Full name",
        email: "Email",
        emailPh: "you@email.com",
        phone: "Phone",
        phonePh: "(305) 000-0000",
        message: "Message",
        messagePh: "How can we help?",
      },
    },
    footer: {
      blurb:
        "Bilingual legal marketplace connecting clients with verified attorneys. Free for clients. Lawyers pay per lead.",
      cols: [
        {
          title: "Platform",
          links: [
            { label: "How it works", href: "#como-funciona" },
            { label: "Areas", href: "#areas" },
            { label: "Verification", href: "#verificacion" },
            { label: "Pricing", href: "#precios" },
          ],
        },
        {
          title: "Legal",
          links: [
            { label: "Legal notice", href: "#aviso-legal" },
            { label: "Contact", href: "#contacto" },
            { label: "Resources", href: "#recursos" },
          ],
        },
      ],
      disclaimer:
        "D2LE2 Law is a technology marketplace. We do not provide legal advice and we are not a law firm. We do not create an attorney-client relationship.",
      copyright: "D2LE2 Law. Legal marketplace. All rights reserved.",
    },
    chat: {
      online: "Online",
      lawyersOnline: "lawyers online",
      availableNow: "Available now",
      minimize: "Minimize chat",
      open: "Open chat",
      close: "Close chat",
      placeholder: "Type your message...",
      attach: "Attach",
      send: "Send message",
      messages: [
        {
          from: "bot" as const,
          text: "Hi! Are you a client seeking help or a lawyer looking for leads?",
          time: "10:30 AM",
        },
        {
          from: "me" as const,
          text: "I want to know how the platform works.",
          time: "10:31 AM",
        },
        {
          from: "bot" as const,
          text: "Clients start their case for free. Lawyers review anonymized leads and pay only when unlocking contact.",
          time: "10:32 AM",
        },
      ],
    },
    phone: "(305) 987-0000",
    phoneHref: "tel:+13059870000",
  },
} as const;

export type Content = (typeof content)[Locale];
